version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data:/var/jenkins_data
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins-net

  
  jenkins-db:
    image: postgres:13
    container_name: jenkins-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=jenkins
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - jenkins_db_data:/var/lib/postgresql/data
    networks:
      - jenkins-net

volumes:
  jenkins_home:
    driver: local
  jenkins_db_data:
    driver: local

networks:
  jenkins-net:
    driver: bridge